### DISCUSSION TITLE
Extra keys not allowed

### DISCUSSION THREAD

**Discussion by Humphrey181** [jbergler/hass-ttlock#194] [Q&A]
I've just got the HA integrations working and returning the info I need.

As an aside, for those that are following.
- the wording in the lock setup instructions is not clear about which username/passwords are required.  I spent a lot of time using my website developer codes and getting error after error until eventually a search on here found that I should have been using the phone app codes.  
- also, the line in the instructions reading _Once the integration is working you should receive a system notification with the webhook url_ should read _receive the webhook in the Home Assistant system notifications area_.  Again, I only found this information from a github search
- these are not criticisms but suggestions for clarifications that will make life easier for others

My issue is that any attempt to write a script in HA gives me the same error - _Failed to perform the action script/lock_turn_on_autolock. extra keys not allowed @ data['device_id']_.  Where do I troubleshoot this issue?  I simply select the lock in the UI on HA.  As far as I know, that's all there is to do.  I checked there are no apparently special characters in the lock ID.  What am I missing here?

Here is the YAML for the autolock script with device_id randomised.  There are no extra keys that I can see.  Also, the lock has a max autolock duration of 300 seconds, but the integration dictionary limits this to just 60 seconds - why?

```
sequence:
  - action: ttlock.configure_autolock
    metadata: {}
    data:
      enabled: true
      seconds: 60
    target:
      device_id: f4f70d3db6b17f205f6dcd0bd0e28bdc
alias: LOCK - Turn on AutoLock
description: ""
```
