### ISSUE TITLE
Passage mode auto unlock not working

### ISSUE THREAD

**Issue by lsellens** [jbergler/hass-ttlock#101]
When calling the passage mode on if I enable auto unlock the lock does show it enters passage mode, but the lock does not auto unlock. If I then unlock the door it will stay unlocked.
### To Reproduce
```
service: ttlock.configure_passage_mode
metadata: {}
data:
  enabled: true
  auto_unlock: true
  all_day: true
target:
  entity_id: lock.pantry
```

### Expected behavior
lock to unlock
but it does not unless I then send a unlock command or manually unlock it
